# 판다스

### 1.판다스 사용 준비

In [3]:
import pandas as pd
pd.__version__

'2.3.3'

### 2. 시리즈 객체의 생성과 속성

In [6]:
numbers = [1,2,3,4,5]
list_sr = pd.Series(numbers)
print(list_sr)
type(list_sr)

0    1
1    2
2    3
3    4
4    5
dtype: int64

pandas.core.series.Series

In [9]:
print(list_sr.dtype, list_sr.shape, list_sr.size, list_sr.name)

int64 (5,) 5 None

In [12]:
dict_data = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
dict_sr = pd.Series(dict_data)
print(dict_sr)
print(dict_sr.dtype, dict_sr.shape, dict_sr.size, dict_sr.name)

a    1
b    2
c    3
d    4
e    5
dtype: int64
int64 (5,) 5 None

In [13]:
list_sr.name = 'mySeries'
list_sr

0    1
1    2
2    3
3    4
4    5
Name: mySeries, dtype: int64

In [14]:
list_sr.name

'mySeries'

In [16]:
sr1 = pd.Series(numbers, dtype=float) # dtype=np.float32 , import numpy as np
sr1

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [18]:
chars = 'a b c d e'.split()
sr3 = pd.Series(numbers, index=chars, name='MySeries')
sr3

a    1
b    2
c    3
d    4
e    5
Name: MySeries, dtype: int64

In [20]:
sr3.index, sr3.values # pandas에서는 string은 object로 나온다

(Index(['a', 'b', 'c', 'd', 'e'], dtype='object'), array([1, 2, 3, 4, 5]))

In [23]:
list_sr.index

RangeIndex(start=0, stop=5, step=1)

### 3. 데이터프레임 객체 다루기
#### 3-1 데이터프레임 객체의 생성과 속성 수정

In [26]:
numbers = [1,2,3,4,5]
pd1 = pd.DataFrame(numbers)
pd1

   0
0  1
1  2
2  3
3  4
4  5

In [27]:
pd2 = pd.DataFrame(numbers, columns=['number'])
pd2

   number
0       1
1       2
2       3
3       4
4       5

In [30]:
score = [['정약용', 70, 80, 100],
         ['이순신', 100, 80, 70],
         ['이율곡', 90, 95, 90]]

score_df = pd.DataFrame(score)
score_df

     0    1   2    3
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [31]:
score_df.columns = ['이름', '국어', '영어', '수학']
score_df

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [32]:
score_df2 = pd.DataFrame(score, columns=['이름', '국어', '영어', '수학'])
score_df2

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [33]:
# 데이터프레임 속성 확인
score_df.shape, score_df.index, score_df.columns

((3, 4),
 RangeIndex(start=0, stop=3, step=1),
 Index(['이름', '국어', '영어', '수학'], dtype='object'))

In [35]:
score_df.dtypes

이름    object
국어     int64
영어     int64
수학     int64
dtype: object

In [37]:
print(score_df.values)

[['정약용' 70 80 100]
 ['이순신' 100 80 70]
 ['이율곡' 90 95 90]]

### 3-2. 데이터프레임의 열(칼럼) 추가

In [48]:
score_dict = {
    '이름' : ['정약용', '이순신', '이율곡', '홍길동'],
    '국어' : [70,100,90,85],
    '영어' : [80,80,95,100],
    '수학' : [100,70,90,90]
}

score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [75]:
# 컬럼 추가 ('사회')
score_df['사회'] = [85,88,92,96]  #score_df['사회'] = 100 하면 값을 전부 100으로 만들어줌 
score_df

    이름   국어   영어   수학  사회
0  정약용   70   80  100  85
1  이순신  100   80   70  88
2  이율곡   90   95   90  92
3  홍길동   85  100   90  96

In [76]:
score_df['총점'] = score_df['국어'] + score_df['영어'] + score_df['수학'] + score_df['사회']
score_df

    이름   국어   영어   수학  사회   총점
0  정약용   70   80  100  85  335
1  이순신  100   80   70  88  338
2  이율곡   90   95   90  92  367
3  홍길동   85  100   90  96  371

In [77]:
score_df['평균'] = score_df.총점 / 4  # 처음 컬럼을 추가할거면 []를 써야하지만 이미 있는 컬럼이면 df.컬럼명
score_df

    이름   국어   영어   수학  사회   총점     평균
0  정약용   70   80  100  85  335  83.75
1  이순신  100   80   70  88  338  84.50
2  이율곡   90   95   90  92  367  91.75
3  홍길동   85  100   90  96  371  92.75

In [57]:
x = [0,1,2,3,4,5]
y = [0,2,4,6,8,10]
df = pd.DataFrame()
df['x'] = x
df['y'] = y
df['x * y'] = df.x * df.y
df

   x   y  x * y
0  0   0      0
1  1   2      2
2  2   4      8
3  3   6     18
4  4   8     32
5  5  10     50

#### 3-4. 데이터프레임의 행/열 삭제, 인덱스 초기화

In [59]:
score_dict = {
    '이름' : ['정약용', '이순신', '이율곡', '홍길동'],
    '국어' : [70,100,90,85],
    '영어' : [80,80,95,100],
    '수학' : [100,70,90,90]
}

score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [62]:
score_df.drop(['이름'], axis=1)

    국어   영어   수학
0   70   80  100
1  100   80   70
2   90   95   90
3   85  100   90

In [65]:
new_df = score_df.drop([0,2], axis=0)
new_df

    이름   국어   영어  수학
1  이순신  100   80  70
3  홍길동   85  100  90

In [68]:
new_df.reset_index()

   index   이름   국어   영어  수학
0      1  이순신  100   80  70
1      3  홍길동   85  100  90

In [72]:
new_df.reset_index(drop=True, inplace=True)
new_df  # inplace = true 이면 return이 없기 때문에 위에 줄 1개만 실행하면 아무것도 안나온다

    이름   국어   영어  수학
0  이순신  100   80  70
1  홍길동   85  100  90

#### 3-5 데이터의 접근

##### 3-5-1. 직접 접근 방식

In [78]:
# 직접 접근 방식
score_df

    이름   국어   영어   수학  사회   총점     평균
0  정약용   70   80  100  85  335  83.75
1  이순신  100   80   70  88  338  84.50
2  이율곡   90   95   90  92  367  91.75
3  홍길동   85  100   90  96  371  92.75

In [79]:
score_df['이름']

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: object

In [81]:
score_df[['이름', '총점']] # 컬럼 slicing은 안된다

    이름   총점
0  정약용  335
1  이순신  338
2  이율곡  367
3  홍길동  371

In [83]:
score_df[1] #Keyerror

KeyError: 1

In [84]:
score_df[1:2]

    이름   국어  영어  수학  사회   총점    평균
1  이순신  100  80  70  88  338  84.5

In [85]:
score_df[1:]

    이름   국어   영어  수학  사회   총점     평균
1  이순신  100   80  70  88  338  84.50
2  이율곡   90   95  90  92  367  91.75
3  홍길동   85  100  90  96  371  92.75

In [87]:
score_df[1:][['이름','총점']]

    이름   총점
1  이순신  338
2  이율곡  367
3  홍길동  371

##### 3-5-2. boolean indexing

In [91]:
score_df[score_df.수학 > 80]

    이름  국어   영어   수학  사회   총점     평균
0  정약용  70   80  100  85  335  83.75
2  이율곡  90   95   90  92  367  91.75
3  홍길동  85  100   90  96  371  92.75

In [94]:
score_df[(score_df.국어 > 80) & (score_df.영어 < 90)]

    이름   국어  영어  수학  사회   총점    평균
1  이순신  100  80  70  88  338  84.5

In [95]:
score_df[score_df.이름.isin(['정약용','이순신'])]

    이름   국어  영어   수학  사회   총점     평균
0  정약용   70  80  100  85  335  83.75
1  이순신  100  80   70  88  338  84.50

##### 3-5-3. 인덱서를 이용한 정석 접근(loc, iloc)

In [99]:
score_df

    이름   국어   영어   수학  사회   총점     평균
0  정약용   70   80  100  85  335  83.75
1  이순신  100   80   70  88  338  84.50
2  이율곡   90   95   90  92  367  91.75
3  홍길동   85  100   90  96  371  92.75

In [97]:
score_df.loc[0, '국어']

np.int64(70)

In [98]:
score_df.loc[0:2, '국어':'수학']

    국어  영어   수학
0   70  80  100
1  100  80   70
2   90  95   90

In [102]:
score_df.iloc[0, 1] # int값만 넣어야한다

np.int64(70)

In [104]:
score_df.iloc[0:2, 1:3]

    국어  영어
0   70  80
1  100  80

#### 4. 데이터프레임의 파일 로딩, 데이터 확인

In [115]:
filename = './data/sample_data.csv'
sample_df = pd.read_csv(filename)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [116]:
sample_df.head(3)

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN

In [117]:
sample_df.tail()

      Name   Age Gender      City
2  Charlie  22.0      M       NaN
3    David  29.0      M   Chicago
4   Edward   NaN      M   Houston
5    Alice  24.0      F  New York
6    Susan  32.0      F   Houston

In [109]:
sample_df.shape

(7, 4)

In [110]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Age     5 non-null      float64
 2   Gender  7 non-null      object
 3   City    6 non-null      object
dtypes: float64(1), object(3)
memory usage: 352.0+ bytes

In [111]:
len(sample_df)

7

In [112]:
sample_df.describe()

             Age
count   5.000000
mean   26.200000
std     4.147288
min    22.000000
25%    24.000000
50%    24.000000
75%    29.000000
max    32.000000

In [113]:
sample_df.value_counts(dropna=True)

Name   Age   Gender  City
Alice  24.0  F       New York    2
David  29.0  M       Chicago     1
Susan  32.0  F       Houston     1
Name: count, dtype: int64

In [114]:
sample_df.value_counts(dropna=False)

Name     Age   Gender  City
Alice    24.0  F       New York       2
Bob      NaN   M       Los Angeles    1
Charlie  22.0  M       NaN            1
David    29.0  M       Chicago        1
Edward   NaN   M       Houston        1
Susan    32.0  F       Houston        1
Name: count, dtype: int64

In [118]:
sample_df['Gender'].value_counts()

Gender
M    4
F    3
Name: count, dtype: int64