## 1. 데이터 로딩 및 확인

In [1]:
import pandas as pd
filename = './data/bccard_201906.csv'
bc_df = pd.read_csv(filename)
bc_df

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52
3,3,201906,11,서울특별시,1144,마포구,11440660,서교동,80,음식,...,내국인,11,서울특별시,1138,은평구,1,20대,1,44174450,1790
4,4,201906,11,서울특별시,1120,성동구,11200550,사근동,80,음식,...,내국인,11,서울특별시,1120,성동구,1,20대,1,60338146,3536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99996,99996,201906,11,서울특별시,1165,서초구,11650520,서초2동,30,생활,...,내국인,43,충청북도,4311,청주시,1,50대,4,50600,10
99997,99997,201906,11,서울특별시,1117,용산구,11170520,용산2가동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,40대,2,38640,7
99998,99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,...,내국인,28,인천광역시,2817,미추홀구,2,30대,2,340590,15
99999,99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,...,내국인,44,충청남도,4413,천안시,1,20대,2,117100,3
100000,100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

### 1-1 앞부분 10개

In [2]:
bc_df.head(10)

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52
3,3,201906,11,서울특별시,1144,마포구,11440660,서교동,80,음식,...,내국인,11,서울특별시,1138,은평구,1,20대,1,44174450,1790
4,4,201906,11,서울특별시,1120,성동구,11200550,사근동,80,음식,...,내국인,11,서울특별시,1120,성동구,1,20대,1,60338146,3536
5,5,201906,11,서울특별시,1114,중구,11140540,회현동,10,T&E,...,내국인,47,경상북도,4713,경주시,2,30대,2,3759530,463
6,6,201906,11,서울특별시,1168,강남구,11680521,논현1동,30,생활,...,내국인,11,서울특별시,1150,강서구,2,20대,1,1461800,274
7,7,201906,11,서울특별시,1171,송파구,11710646,장지동,30,생활,...,내국인,11,서울특별시,1171,송파구,1,40대,3,557490,48
8,8,201906,11,서울특별시,1168,강남구,11680656,도곡2동,30,생활,...,내국인,45,전라북도,4511,전주시,2,30대,2,36909050,3465
9,9,201906,11,서울특별시,1114,중구,11140550,명동,10,T&E,...,내국인,28,인천광역시,2817,미추홀구,1,20대,1,10002400,117

### 1-2 뒷부분(10개)

In [8]:
bc_df.tail(10)

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
99991,99991,201906,11,서울특별시,1174,강동구,11740550,고덕1동,30,생활,...,내국인,41,경기도,4136,남양주시,2,40대,3,68980,15
99992,99992,201906,11,서울특별시,1171,송파구,11710642,문정2동,10,T&E,...,내국인,11,서울특별시,1171,송파구,2,60대 이상,5,3350000,10
99993,99993,201906,11,서울특별시,1132,도봉구,11320514,창4동,30,생활,...,내국인,41,경기도,4117,안양시,2,40대,3,12200,3
99994,99994,201906,11,서울특별시,1168,강남구,11680545,압구정동,99,기타,...,내국인,11,서울특별시,1126,중랑구,1,30대,2,1432000,3
99995,99995,201906,11,서울특별시,1114,중구,11140520,소공동,30,생활,...,내국인,45,전라북도,4511,전주시,1,40대,3,971830,13
99996,99996,201906,11,서울특별시,1165,서초구,11650520,서초2동,30,생활,...,내국인,43,충청북도,4311,청주시,1,50대,4,50600,10
99997,99997,201906,11,서울특별시,1117,용산구,11170520,용산2가동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,40대,2,38640,7
99998,99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,...,내국인,28,인천광역시,2817,미추홀구,2,30대,2,340590,15
99999,99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,...,내국인,44,충청남도,4413,천안시,1,20대,2,117100,3
100000,100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

### 1-3 데이터수

In [6]:
len(bc_df)

100001

### 2. 서울시 거주/비거주 고객 비교 분석

### 2-1 서울시 거주/비거주(seoul, non_seoul)

In [ ]:
seoul = bc_df[bc_df['CSTMR_MEGA_CTY_NM'] == '서울특별시']
non_seoul = bc_df[bc_df['CSTMR_MEGA_CTY_NM'] != '서울특별시']

        Unnamed: 0  REG_YYMM  MEGA_CTY_NO MEGA_CTY_NM  CTY_RGN_NO CTY_RGN_NM  \
5                5    201906           11       서울특별시        1114         중구
8                8    201906           11       서울특별시        1168        강남구
9                9    201906           11       서울특별시        1114         중구
10              10    201906           11       서울특별시        1144        마포구
13              13    201906           11       서울특별시        1156       영등포구
...            ...       ...          ...         ...         ...        ...
99995        99995    201906           11       서울특별시        1114         중구
99996        99996    201906           11       서울특별시        1165        서초구
99998        99998    201906           11       서울특별시        1156       영등포구
99999        99999    201906           11       서울특별시        1141       서대문구
100000      100000    201906           11       서울특별시        1135        노원구

        ADMI_CTY_NO ADMI_CTY_NM  MAIN_BUZ_CODE MAIN_BUZ_DESC  ...  \
5          11140540         회현동             10           T&E  ...
8          11680656        도곡2동             30            생활  ...
9          11140550          명동             10           T&E  ...
10         11440555         아현동             30            생활  ...
13         11560515       영등포본동             30            생활  ...
...             ...         ...            ...           ...  ...
99995      11140520         소공동             30            생활  ...
99996      11650520        서초2동             30            생활  ...
99998      11560535        영등포동             30            생활  ...
99999      11410585         신촌동             40            쇼핑  ...
100000     11350710        상계9동             20            문화  ...

        CSTMR_GUBUN CSTMR_MEGA_CTY_NO  CSTMR_MEGA_CTY_NM CSTMR_CTY_RGN_NO  \
5               내국인                47               경상북도             4713
8               내국인                45               전라북도             4511
9               내국인                28              인천광역시             2817
10              내국인                26              부산광역시             2617
13              내국인                41                경기도             4117
...             ...               ...                ...              ...
99995           내국인                45               전라북도             4511
99996           내국인                43               충청북도             4311
99998           내국인                28              인천광역시             2817
99999           내국인                44               충청남도             4413
100000          내국인                41                경기도             4115

       CSTMR_CTY_RGN_NM  SEX_CTGO_CD AGE_VAL  FLC       AMT   CNT
5                   경주시            2     30대    2   3759530   463
8                   전주시            2     30대    2  36909050  3465
9                  미추홀구            1     20대    1  10002400   117
10                   동구            2     30대    2  43811379  1426
13                  안양시            1     50대    3    279850    54
...                 ...          ...     ...  ...       ...   ...
99995               전주시            1     40대    3    971830    13
99996               청주시            1     50대    4     50600    10
99998              미추홀구            2     30대    2    340590    15
99999               천안시            1     20대    2    117100     3
100000             의정부시            1     40대    3   5227500     7

[45851 rows x 24 columns]

### 2-2 고객 수, 총 소비액, 카드 이용 건수

In [18]:
print(f"서울시 거주 고객수 : {len(seoul):,} 명\n서울시 비거주 고객수 : {len(non_seoul):,} 명")
print(f"서울시 거주 총 소비액 : {seoul['AMT'].sum():,} 원\n서울시 비거주 총 소비액 : {non_seoul['AMT'].sum():,} 원")
print(f"서울시 거주 총 이용건수 : {seoul['CNT'].sum():,} 건\n서울시 비거주 총 이용건수 : {non_seoul['CNT'].sum():,} 건")

서울시 거주 고객수 : 54,150 명
서울시 비거주 고객수 : 45,851 명
서울시 거주 총 소비액 : 119,663,142,676 원
서울시 비거주 총 소비액 : 146,587,135,822 원
서울시 거주 총 이용건수 : 5,542,462 건
서울시 비거주 총 이용건수 : 4,950,200 건

## 3. 편의점 소비 정보 분석

### 3-1 편의점 소비액, 강남구 소비액

In [25]:
cstore_total_amt = bc_df[bc_df['TP_BUZ_NO'] == 4010]['AMT'].sum()
gangnam_total_amt = bc_df[bc_df['CTY_RGN_NM'] == '강남구']['AMT'].sum()
print(f"편의점 소비액 : {cstore_total_amt:,} 원")
print(f"강남구 소비액 : {gangnam_total_amt:,} 원")

편의점 소비액 : 7,299,184,098 원
강남구 소비액 : 35,535,648,502 원

### 3-2 강남구 편의점 소비액

In [29]:
gangnam_cstore_df = bc_df[(bc_df['CTY_RGN_NM'] == '강남구') & (bc_df['TP_BUZ_NO'] == 4010)]
gangnam_cstore_amt = gangnam_cstore_df['AMT'].sum()
print(f"강남구 편의점 소비액 : {gangnam_cstore_amt:,} 원")

강남구 편의점 소비액 : 707,275,140 원

### 3-3 강남구 편의점 소비액 중 강남구 거주자와 비거주자의 소비액 비교

In [35]:
resident_cstore_amt = gangnam_cstore_df[gangnam_cstore_df['CSTMR_CTY_RGN_NM'] == '강남구']['AMT'].sum()
non_resident_cstore_amt = gangnam_cstore_df[gangnam_cstore_df['CSTMR_CTY_RGN_NM'] != '강남구']['AMT'].sum()
print(f"강남구 편의점 소비액: {gangnam_cstore_amt:,.0f}원")
print(f"강남구 거주자 편의점 소비액: {resident_cstore_amt:,} 원")
print(f"강남구 비거주자 편의점 소비액: {non_resident_cstore_amt:,} 원")

강남구 편의점 소비액: 707,275,140원
강남구 거주자 편의점 소비액: 288,379,890 원
강남구 비거주자 편의점 소비액: 418,895,250 원